networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data: {}
  prometheus-data: {}

services:
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_USE_SSL: ${USE_SSL:-false}
        VITE_BACKEND_PORT: ${BACKEND_PORT:-8000}
        USE_SELF_SIGNED_CERT: ${USE_SELF_SIGNED_CERT:-false}
    image: smart-lift-frontend
    container_name: smart-lift-frontend
    restart: unless-stopped
    ports:
      - ${FRONTEND_PORT:-8080}:80
      - ${FRONTEND_SSL_PORT:-8443}:443
    volumes:
      - ./certs:/etc/nginx/ssl:ro
    environment:
      TZ: Europe/Berlin

  backend:
    build: 
      context: ./backend
    image: smart-lift-backend
    container_name: smart-lift-backend
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT:-8000}:8000
    volumes:
      - ./certs:/code/app/certs
      - ./binaries:/code/app/binaries
      - ./lift_info.json:/code/app/lift_info.json
    environment:
      TZ: Europe/Berlin
      HOSTNAME: ${HOSTNAME:-localhost}
      BACKEND_PORT: ${BACKEND_PORT:-8000}
      USE_SSL: ${USE_SSL:-false}
      USE_SELF_SIGNED_CERT: ${USE_SELF_SIGNED_CERT:-false}

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    environment:
      - TZ=Europe/Berlin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./certs/server.crt:/etc/prometheus/server.crt
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring
    environment:
      - TZ=Europe/Berlin