global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'smart-lift'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/server.crt
    scrape_interval: 5s
    static_configs:
      - targets: ['smart-lift:8000']
